# Generated by Django 5.0.1 on 2024-01-23 06:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KDC', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'id'},
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default=datetime.datetime(2024, 1, 23, 6, 4, 29, 40567, tzinfo=datetime.timezone.utc), max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=datetime.datetime(2024, 1, 23, 6, 4, 58, 866652, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
