# Generated by Django 5.0.1 on 2024-01-23 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default=datetime.datetime(2024, 1, 23, 6, 4, 29, 39910, tzinfo=datetime.timezone.utc), max_length=10),
        ),
    ]
